### ISSUE TITLE
Multiple Apps / Domains

### ISSUE THREAD

**Issue by dholms** [fission-suite/fission#129]
# Summary

## Problem

Domain registration (https://github.com/fission-suite/web-api/issues/128) can only provision one domain: `{username}.runfission.com`

### Impact

User's can only have one domain through fission. And that domain doesn't offer much contextual information (since it's just the username)

## Solution

Allow multiple custom subdomains per user
- create a new table user_domains that stores which domains are associated with each user (something like: userID, subdomain, and time created)
- before creating a new subdomain, check that a user hasn't already claimed that subdomain

**Comment by bechurch** [comment]
@fission-suite/core How do we want to deal with usernames and custom sites? As far as I can see it we have 3 options:
1. Ensure users always own their username subdomain name. This means a custom domain would equate to a username in our system. So that a user could not signup with that username if a custom domain was created with an existing name
1. Partition the url scheme so that username subdomains and other custom domains are different. A username subdomain would be at `username.fission.app` where as other custom domains are at `customsub.demo.fission.app`
1. Don't give username subdomains as a default. A users first site and every site after will live under specifically given or randomly generated subdomains. If the username is already taken as a subdomain we don't care.

I believe option 3 is best.

**Comment by bmann** [comment]
I think we want to provision “userid subdomains” as a special case along with our identity system. 

And yes, I think 3 is best. As part of register, you choose a username. If the subdomain is available, you get it, otherwise you get a random subdomain. This is filled in for you in fission.yaml, as well as returned. “Thanks for registering. We’ve created a default subdomain for you at USERNAME.fission.name. Check fission.yaml for more details or add a domain with fission domain add”

Unless you add an extra argument to name your app, Heroku gives you a random generated one. You have email address as username on Heroku. Plus named teams (I think team names need to be unique). We don’t want that for a variety of reasons, including that non email sign ups could be supported. 

Also, rather than being subdomain focused, shouldn’t this be domain focused @dholms? Or do we think that every app has a unique subdomain as well as its public domain? I _think_ we want a subdomain that something is definitely accessible by. 

I _think_ canonical_domain_id and we need ANOTHER table, Domains, with domain name, domainID, subdomainID (and some other stuff, like whether we think we are hosting the NS or not)

Then we have many domains to one subdomain, including one canonical domain ID.
