### ISSUE TITLE
Only update DNSLink when content is available on gateway

### ISSUE THREAD

**Issue by icidasset** [fission-suite/fission#362]
## Problem

Otherwise data may get lost.
See https://github.com/fission-suite/ts-sdk/issues/77 for more context.

## Solution

Wait for content to be available and then update DNSLink.
Also report progress to API consumer.

Related to #312

**Comment by expede** [comment]
Not a bug per se — more a question of tradeoffs, since an online peer with those changes can serve them instantly.

The idea is that by making this change the server will behave more like a traditional uploader, and only provide the ID to others when it has a copy of the data. We can _additionally_ broadcast the new Merkle root over IPNS pubsub (#363)

**Comment by icidasset** [comment]
We already have this right?
